version: '0.1'
# Will search from these documents, item at first position takes higher priority 
document_dirs:
# - C:\Users\zlzk\zhny-projects\API-drought-ET-irrigation
# Files with these extensions will be token account in
- C:\Users\zlzk\zhny-projects\drought-SW-irrigation\pyfao56-main\tests\test8_test
# - C:\Users\zlzk\zhny-projects\drought-SW-irrigation\pyfao56-main\src
extensions:
- txt
- md
- properties
- py
exclude:
- /Users/vzhong/suoha/materials/*
